# Generated by Django 3.2.7 on 2021-09-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='type',
        ),
        migrations.AddField(
            model_name='attendance',
            name='in_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='out_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='On Time', max_length=100),
        ),
    ]
