# Generated by Django 3.2.7 on 2021-09-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='actual_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
