# Generated by Django 3.2.7 on 2021-09-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_employee_actual_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='actual_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
