# Generated by Django 3.2.7 on 2021-09-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_employee_actual_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='actual_image',
        ),
    ]
