# Generated by Django 3.2.7 on 2021-09-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210918_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
